[tools]
"github:1Axen/blink" = "latest"
"github:Kampfkarren/selene" = "latest"
"github:johnnymorganz/stylua" = "latest"
"github:lune-org/lune" = "latest"
"github:rojo-rbx/rojo" = "latest"
"github:seaofvoices/darklua" = "latest"
