[tools]
rojo = "rojo-rbx/rojo@7.6.1"
selene = "Kampfkarren/selene@0.30.1"
darklua = "seaofvoices/darklua@0.18.0"
blink = "1Axen/blink@0.18.7"
lune = "lune-org/lune@0.10.4"
stylua = "johnnymorganz/stylua@2.4.1"
