on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - uses: CompeyDev/setup-rokit@1d9390883f7ebce19d48f5b8d006e11d387c92ab # v0.2.1

      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6
        with:
          version: latest

      - name: install packages
        run: pnpm install --ignore-scripts --no-frozen-lockfile

      - name: run linter
        run: pnpm lint

      - name: build game
        run: pnpm prod:build
